#!/usr/bin/env bash
# shellcheck disable=SC2162

SSH_CONFIG_FILE="$HOME/.ssh/config"
DEFAULT_SSH_PORT="22"
DEFAULT_SSH_USERNAME=""
DEVICES="air pro"
if [ -n "$1" ]; then
  DEVICES="$1"
fi

if [ -n "$2" ]; then
  DEFAULT_SSH_USERNAME="$2"
fi

if [ -n "$3" ]; then
  DEFAULT_SSH_PORT="$3"
fi

function updateSshConfig() {
  local devices="$1"

  TAILSCALE_STATUS=$(tailscale status)

  for device in $devices; do
  echo "$TAILSCALE_STATUS"
  line=$(echo "$TAILSCALE_STATUS" | grep macOS | grep "$device" | sort | uniq)
  device_ip=$(echo "$line" | awk '{print $1}')
  device_name=$(echo "$line" | awk '{print $2}')

  # is host in $HOME/.ssh/config
  if ! grep "$device" < "$SSH_CONFIG_FILE" >/dev/null; then
    echo "No host \"$device_ip\" found in \"$SSH_CONFIG_FILE\""

  if [ -n "$DEFAULT_SSH_USERNAME" ]; then
    username="$DEFAULT_SSH_USERNAME"
  else
    #shellcheck disable=SC2162
    read -p "Enter username for device \"$device_name\": " username
  fi


  if [ -n "$DEFAULT_SSH_PORT" ]; then
    port="$DEFAULT_SSH_PORT"
  else
    read -p "Enter ssh port for device \"$device_name\": " port
  fi
  if [ -z "$port" ]; then
    port=22
  fi

  # add host ssh config to $SSH_CONFIG_FILE
  /bin/cat >> "$SSH_CONFIG_FILE" << EOF
# generated by tailscale_devices_to_ssh_config.sh
Host "t$device"
  HostName $device_ip
  User $username
  Port $port
EOF
  fi
done
}

# update ssh config for defined devices
updateSshConfig "$DEVICES"
